@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace odel {
      class model.Question {
          - answers : List<String>
          - audioName : String
          - choices : List<String>
          - isAnswered : boolean
          - pictureName : String
          - points : int
          - questionContent : String
          - questionType : String
          - topic : String
          + Question()
          + getAnswers()
          + getAudioFilePath()
          + getChoices()
          + getPictureFilePath()
          + getPoints()
          + getQuestionContent()
          + getQuestionType()
          + getTopic()
          + isAnswered()
          + isAnsweredRight()
          + questionAnswered()
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.QuestionBank {
          - currentTopic : String
          {static} - topicQuestionMap : Map<String, List<Question>>
          + QuestionBank()
          + getAllTopics()
          + getCurrentQuestion()
          + getCurrentTopic()
          + publish()
          + reset()
          {static} - addQuestion()
          - chooseQuestion()
          {static} - loadQuestions()
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.QuestionStatistic {
          {static} - SKILL_ACCURACY_THRESHOLD : double
          - rightNum : int
          - score : int
          - topicStatisticMap : Map<String, TopicStatistic>
          - totalAnsweredNum : int
          + QuestionStatistic()
          + getRightAns()
          + getScore()
          + getSkilledTopics()
          + getTopicStatisticMap()
          + getTotalAnsweredNum()
          + getWeakedTopics()
          + publish()
          + reset()
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.QuestionTime {
          {static} + DELAY_TIME : int
          {static} + TOTAL_TIME : int
          - leftTime : int
          + getLeftTime()
          + isRedAlert()
          + isTimeRunOut()
          + publish()
          + resetLeftTime()
      }
    }
  }
  

  namespace  {
    namespace odel {
      class model.TopicStatistic {
          - accuracy : double
          - rightNum : int
          - score : int
          - topic : String
          - totalAnsweredNum : int
          + TopicStatistic()
          + getAccuracy()
          + getFormatedAccuracy()
          + getRightNum()
          + getScore()
          + getTopic()
          + getTotalAnsweredNum()
          + update()
      }
    }
  }
  

  model.QuestionBank -up-|> java.util.Observable
  model.QuestionBank o-- model.Question : currentQuestion
  model.QuestionStatistic -up-|> java.util.Observable
  model.QuestionTime -up-|> java.util.Observable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
