@startuml

title __VIEW's Class Diagram__\n

  namespace  {
    namespace iew {
      class view.MyButton {
          - isLastButton : boolean
          + MyButton()
          + MyButton()
          + isLastButton()
          + setLastButton()
          - initUI()
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PuzzleEx {
          - DESIRED_WIDTH : int
          - NUMBER_OF_BUTTONS : int
          - buttons : List<MyButton>
          - height : int
          - image : Image
          - panel : JPanel
          - resized : BufferedImage
          - solution : List<Point>
          - source : BufferedImage
          - width : int
          + PuzzleEx()
          + checkSolution()
          {static} + compareList()
          - getNewHeight()
          - initUI()
          - loadImage()
          - resizeImage()
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.PuzzleEx.ClickAction {
          + actionPerformed()
          - checkButton()
          - updateButtons()
      }
    }
  }
  

  namespace  {
    namespace iew {
      class view.SwingDnDFrame {
          - scrollPane : JScrollPane
          - tabbedPane : JTabbedPane
          - textArea : JTextArea
          + SwingDnDFrame()
          + getTextArea()
      }
    }
  }
  

  view.MyButton -up-|> javax.swing.JButton
  view.PuzzleEx -up-|> javax.swing.JPanel
  view.PuzzleEx o-- view.MyButton : lastButton
  view.PuzzleEx +-down- view.PuzzleEx.ClickAction
  view.PuzzleEx.ClickAction -up-|> javax.swing.AbstractAction
  view.SwingDnDFrame -up-|> javax.swing.JPanel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
