@startuml

title __PERFORMANCE's Class Diagram__\n

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.ChartView {
            + ChartView()
            + update()
            - createChart()
            - createDataset()
            - drawChart()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.ChartView.CustomLabelGenerator {
            + generateAttributedSectionLabel()
            + generateSectionLabel()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.ResultView {
            + ResultView()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.ScoreView {
            - rightNumberLabel : JLabel
            - scoreLabel : JLabel
            - totalNumberLabel : JLabel
            - wrongNumberLabel : JLabel
            + ScoreView()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.TimeView {
            - timeLabel : JLabel
            - timer : Timer
            + TimeView()
            + addTimingListener()
            + startTimer()
            + stopTimer()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace performance {
        class view.performance.TotalView {
            + TotalView()
            - createChart()
            - createDataset()
            - drawBarGraph()
        }
      }
    }
  }
  

  view.performance.ChartView -up-|> javax.swing.JPanel
  view.performance.ChartView +-down- view.performance.ChartView.CustomLabelGenerator
  view.performance.ChartView.CustomLabelGenerator .up.|> org.jfree.chart.labels.PieSectionLabelGenerator
  view.performance.ResultView -up-|> javax.swing.JPanel
  view.performance.ScoreView -up-|> javax.swing.JPanel
  view.performance.TimeView .up.|> java.util.Observer
  view.performance.TimeView -up-|> javax.swing.JPanel
  view.performance.TotalView -up-|> javax.swing.JPanel
  view.performance.TotalView o-- model.QuestionStatistic : questionStatistic


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
