@startuml

title __QUESTION's Class Diagram__\n

  namespace  {
    namespace iew {
      namespace question {
        class view.question.AnswerView {
            + AnswerView()
            + getChoiceView()
            + update()
            - createChoiceView()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        abstract class view.question.ChoiceView {
            {abstract} + displayChoice()
            {abstract} + getUserAnswer()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.ContentView {
            - contentArea : JTextArea
            + ContentView()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.DAndDImpl {
            - inputArea : JTextArea
            + DAndDImpl()
            + displayChoice()
            + getUserAnswer()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.ImageView {
            + ImageView()
            + setImage()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.InputTextImpl {
            - inputArea : JTextArea
            + InputTextImpl()
            + displayChoice()
            + getUserAnswer()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.MultipleChoiceImpl {
            - checkBoxes : ArrayList<JCheckBox>
            + MultipleChoiceImpl()
            + displayChoice()
            + getUserAnswer()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.PuzzleImpl {
            + PuzzleImpl()
            + displayChoice()
            + getUserAnswer()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace question {
        class view.question.SingleChoiceImpl {
            - choiceButtons : ArrayList<JRadioButton>
            - choiceGroup : ButtonGroup
            + SingleChoiceImpl()
            + displayChoice()
            + getUserAnswer()
        }
      }
    }
  }
  

  view.question.AnswerView .up.|> java.util.Observer
  view.question.AnswerView -up-|> javax.swing.JPanel
  view.question.AnswerView o-- view.question.ChoiceView : choiceView
  view.question.AnswerView o-- view.question.ImageView : imageView
  view.question.ChoiceView -up-|> javax.swing.JPanel
  view.question.ContentView .up.|> java.util.Observer
  view.question.ContentView -up-|> javax.swing.JPanel
  view.question.DAndDImpl -up-|> view.question.ChoiceView
  view.question.DAndDImpl o-- view.SwingDnDFrame : swingDnDFrame
  view.question.ImageView -up-|> javax.swing.JLabel
  view.question.InputTextImpl -up-|> view.question.ChoiceView
  view.question.MultipleChoiceImpl -up-|> view.question.ChoiceView
  view.question.PuzzleImpl -up-|> view.question.ChoiceView
  view.question.PuzzleImpl o-- view.PuzzleEx : puzzle
  view.question.SingleChoiceImpl -up-|> view.question.ChoiceView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
