@startuml

title __MAIN's Class Diagram__\n

  namespace  {
    namespace iew {
      namespace main {
        class view.main.ButtonView {
            - nextButton : JButton
            - resetButton : JButton
            - startButton : JButton
            - submitButton : JButton
            - viewResultButton : JButton
            + ButtonView()
            + addNextListener()
            + addResetListener()
            + addStartListener()
            + addSubmitListener()
            + addViewResultListener()
            + disableButton()
            + disableStartButton()
            + disableViewResultButton()
            + enableButton()
            + enableStartButton()
            + enableViewResultButton()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.ControlView {
            + controlPanel : JPanel
            - cardLayout : CardLayout
            + ControlView()
            + getQuestionView()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.LoginView {
            - cancelButton : JButton
            - loginButtonPanel : JPanel
            - loginInfoLabel : JLabel
            - loginTextField : JTextField
            - okButton : JButton
            - username : String
            + LoginView()
            + addOkButtonListener()
            + getLoginTextField()
            + getUsername()
            + setUsername()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.MainFrame {
            - mainFrame : JFrame
            {static} - topicView : TopicView
            + MainFrame()
            {static} + getTopicView()
            + initMainFrame()
            - initComponent()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.PerformanceView {
            + PerformanceView()
            + getTimeView()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.QuestionView {
            + QuestionView()
            + getAnswerView()
            + getContentView()
        }
      }
    }
  }
  

  namespace  {
    namespace iew {
      namespace main {
        class view.main.TopicView {
            - logo : JLabel
            - nameLabel : JLabel
            - topicLabel : JLabel
            - topicRadioButtons : List<JRadioButton>
            + TopicView()
            + addTopicSelectionListener()
            + getTopic()
            + setNameLabel()
        }
      }
    }
  }
  

  view.main.ButtonView -up-|> javax.swing.JPanel
  view.main.ControlView o-- view.main.LoginView : loginView
  view.main.ControlView o-- view.main.QuestionView : questionView
  view.main.LoginView -up-|> javax.swing.JPanel
  view.main.MainFrame -up-|> javax.swing.JFrame
  view.main.PerformanceView .up.|> java.util.Observer
  view.main.PerformanceView -up-|> javax.swing.JPanel
  view.main.PerformanceView o-- view.performance.ChartView : chartView
  view.main.PerformanceView o-- view.performance.ScoreView : scoreView
  view.main.PerformanceView o-- view.performance.TimeView : timeView
  view.main.QuestionView -up-|> javax.swing.JPanel
  view.main.QuestionView o-- view.question.AnswerView : answerView
  view.main.QuestionView o-- view.question.ContentView : contentView
  view.main.TopicView -up-|> javax.swing.JPanel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
